//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyChat
    {
        public int SenderId { get; set; }
        public int SendToId { get; set; }
        public string Message { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
