//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public int Stars { get; set; }
        public string Review { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
